import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistery";
import Navbar from "@/shared/components/navbar";
import QueryProviders from "@/shared/components/provider";
import Footer from "@/shared/components/footer";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={cn("font-sans", geist.variable)}>
      <body className="flex flex-col min-h-screen bg-linear-to-bl from-emerald-100 to-emerald-50">
        <ThemeRegistry>
          <QueryProviders>
            <Navbar />
            <main className="grow">
              {children}
            </main>
            <Footer />
          </QueryProviders>
        </ThemeRegistry>
      </body>
    </html>
  );
}
