import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistery";
import Navbar from "@/components/navbar";
import QueryProviders from "@/components/provider";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col min-h-screen bg-linear-to-bl from-emerald-100 to bg-emerald-50">
        <ThemeRegistry>
          <QueryProviders>
            <Navbar />
            <main className="grow">
              {children}
            </main>
            <Footer />
          </QueryProviders>
        </ThemeRegistry>
      </body>
    </html>
  );
}
